=== XiaolinFunke/WC3FunkeBuildOrderPlanner/SimEngine/Schema/SimulatedTimelinesSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Simulated Timelines Schema",
    "description": "Defines the format for the JSON that represents the timelines for each build order (max 4 for team builds) in the WC3 Build Order Planner",
    "type": "array",
    "items": {
        "description": "Each item represents a single player's build order, in the array of all player build order's for the team",
        "type": "object",
        "minItems": 1,
        "maxItems": 4,
        "properties": {
            "currentSimTime": {
                "description": "The current sim time for this build",
                "type": "integer",
                "minimum": 0
            },
            "currentResources": {
                "description": "The resources currently available to the player at this time",
                "type": "object",
                "properties": {
                    "currentGold": {
                        "description": "The amount of gold the player currently has",
                        "type": "integer",
                        "minimum": 0
                    },
                    "currentLumber": {
                        "description": "The amount of lumber the player currently has",
                        "type": "integer",
                        "minimum": 0
                    },
                    "currentFood": {
                        "description": "The amount of food the player is currently using",
                        "type": "integer",
                        "minimum": 0
                    },
                    "currentFoodMax": {
                        "description": "The current maximum food cap for the player",
                        "type": "integer",
                        "minimum": 0
                    }
                },
                "required": [ "currentGold", "currentLumber", "currentFood", "currentFoodMax" ]
            },
            "activeTimelines": {
                "description": "An array of timelines that have actions on them (which makes them 'active')",
                "type": "array",
                "items": {
                    "$ref": "urn:TimelineObject"
                }
            },
            "inactiveTimelines": {
                "description": "An array of timeline that have no actions on them (which makes them 'inactive')",
                "type": "array",
                "items": {
                    "$ref": "urn:TimelineObject"
                }
            }
        },
        "required": [ "currentSimTime", "currentResources", "activeTimelines", "inactiveTimelines" ]
    }
}

=== XiaolinFunke/WC3FunkeBuildOrderPlanner/Test/TestInput/HuntBuildSimulationOutputTruth.json
[
  {
    "currentSimTime": 1860,
    "activeTimelines": [
      {
        "timelineType": "Wisp",
        "timelineID": 4,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 0,
            "travelTime": 10,
            "startTime": 0,
            "currentWorkerTask": "IDLE",
            "desiredWorkerTask": "GOLD"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 5,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 1,
            "travelTime": 12.0,
            "startTime": 0,
            "currentWorkerTask": "IDLE",
            "desiredWorkerTask": "GOLD"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 6,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 2,
            "travelTime": 15.0,
            "startTime": 0,
            "currentWorkerTask": "IDLE",
            "desiredWorkerTask": "GOLD"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 7,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 3,
            "travelTime": 18.0,
            "startTime": 0,
            "currentWorkerTask": "IDLE",
            "desiredWorkerTask": "GOLD"
          }
        ]
      },
      {
        "timelineType": "Tree of Life",
        "timelineID": 9,
        "actions": [
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 4,
            "name": "Wisp",
            "duration": 140,
            "startTime": 0
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 7,
            "name": "Wisp",
            "duration": 140,
            "startTime": 140
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 9,
            "name": "Wisp",
            "duration": 140,
            "startTime": 280
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 11,
            "name": "Wisp",
            "duration": 140,
            "startTime": 420
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 13,
            "name": "Wisp",
            "duration": 140,
            "startTime": 560
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 17,
            "name": "Wisp",
            "duration": 140,
            "startTime": 700
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 19,
            "name": "Wisp",
            "duration": 140,
            "startTime": 840
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 23,
            "name": "Wisp",
            "duration": 140,
            "startTime": 980
          },
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 25,
            "name": "Wisp",
            "duration": 140,
            "startTime": 1120
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 8,
        "actions": [
          {
            "actionType": "BuildStructureAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 5,
            "name": "Altar of Elders",
            "duration": 600,
            "travelTime": 80,
            "startTime": 0,
            "currentWorkerTask": "IDLE"
          },
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "PERCENT_OF_ONGOING_ACTION",
              "value": 100,
              "actionID": 5
            },
            "actionID": 15,
            "travelTime": 20,
            "startTime": 680,
            "currentWorkerTask": "IDLE",
            "desiredWorkerTask": "LUMBER"
          },
          {
            "actionType": "BuildStructureAction",
            "trigger": {
              "triggerType": "LUMBER_AMOUNT",
              "value": 155
            },
            "actionID": 20,
            "name": "Hunter's Hall",
            "duration": 600,
            "travelTime": 20,
            "startTime": 940,
            "currentWorkerTask": "LUMBER"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 10,
        "actions": [
          {
            "actionType": "BuildStructureAction",
            "trigger": {
              "triggerType": "NEXT_WORKER_BUILT",
              "value": "Wisp"
            },
            "actionID": 6,
            "name": "Moon Well",
            "duration": 500,
            "travelTime": 20,
            "startTime": 140,
            "currentWorkerTask": "IN_PRODUCTION"
          },
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "PERCENT_OF_ONGOING_ACTION",
              "value": 100,
              "actionID": 6
            },
            "actionID": 14,
            "travelTime": 20,
            "startTime": 660,
            "currentWorkerTask": "IDLE",
            "desiredWorkerTask": "LUMBER"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 13,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "NEXT_WORKER_BUILT",
              "value": "Wisp"
            },
            "actionID": 8,
            "travelTime": 15,
            "startTime": 280,
            "currentWorkerTask": "IN_PRODUCTION",
            "desiredWorkerTask": "GOLD"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 14,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "NEXT_WORKER_BUILT",
              "value": "Wisp"
            },
            "actionID": 10,
            "travelTime": 20,
            "startTime": 420,
            "currentWorkerTask": "IN_PRODUCTION",
            "desiredWorkerTask": "LUMBER"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 15,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "NEXT_WORKER_BUILT",
              "value": "Wisp"
            },
            "actionID": 12,
            "travelTime": 20,
            "startTime": 560,
            "currentWorkerTask": "IN_PRODUCTION",
            "desiredWorkerTask": "LUMBER"
          },
          {
            "actionType": "BuildStructureAction",
            "trigger": {
              "triggerType": "LUMBER_AMOUNT",
              "value": 50
            },
            "actionID": 26,
            "name": "Ancient of War",
            "duration": 600,
            "travelTime": 20,
            "startTime": 1140,
            "currentWorkerTask": "LUMBER"
          }
        ]
      },
      {
        "timelineType": "Altar of Elders",
        "timelineID": 11,
        "actions": [
          {
            "actionType": "BuildUnitAction",
            "trigger": {
              "triggerType": "ASAP"
            },
            "actionID": 8,
            "name": "Keeper of the Grove",
            "duration": 550,
            "startTime": 680
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 16,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "NEXT_WORKER_BUILT",
              "value": "Wisp"
            },
            "actionID": 16,
            "travelTime": 20,
            "startTime": 700,
            "currentWorkerTask": "IN_PRODUCTION",
            "desiredWorkerTask": "LUMBER"
          },
          {
            "actionType": "BuildStructureAction",
            "trigger": {
              "triggerType": "LUMBER_AMOUNT",
              "value": 35
            },
            "actionID": 28,
            "name": "Moon Well",
            "duration": 500,
            "travelTime": 20,
            "startTime": 1280,
            "currentWorkerTask": "LUMBER"
          }
        ]
      },
      {
        "timelineType": "Wisp",
        "timelineID": 17,
        "actions": [
          {
            "actionType": "WorkerMovementAction",
            "trigger": {
              "triggerType": "NEXT_WORKER_BUILT",
